### ISSUE TITLE
Function, methods and structs aren't highlighted

### ISSUE THREAD

**Issue by GrayJack** [miqh/atom-language-rust#17]
Using 0.14

Examples
 * Red: functions and methods
 * Green: Structs

![25-10-2018-23-29](https://user-images.githubusercontent.com/17973728/47541039-26b36400-d8ae-11e8-955d-9d2d5c42ca1f.png)

![25-10-2018-23-31](https://user-images.githubusercontent.com/17973728/47541064-3fbc1500-d8ae-11e8-8fc0-f2c981ef9719.png)

**Comment by miqh** [comment]
Hello @GrayJack,

Yes, all the cases you've pointed out I've been well-aware of for a long time.

This was an opinionated decision I made when originally authoring the package in the name of consistency given the limitations of TextMate-like grammar definitions.

I've provided an notice update release ([0.14.1][]) advising those writing Rust in Atom to disable this package in favour of the new parsing system developed by the Atom team.

[0.14.1]: https://github.com/miqh/atom-language-rust/releases/tag/v0.14.1
